#if !canImport(ObjectiveC)
    import XCTest

    extension FirebladePALTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__FirebladePALTests = [
            ("testPlatformSetup", testPlatformSetup),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(FirebladePALTests.__allTests__FirebladePALTests),
        ]
    }
#endif
