name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux-test-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Restore APT cache
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt

      - name: Restore cached SPM dependencies
        uses: actions/cache@v3
        with:
          path: .build
          key: swiftpm-${{ runner.os }}-${{ inputs.swift-version }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            swiftpm-${{ runner.os }}-${{ inputs.swift-version }}-
            swiftpm-${{ runner.os }}-

      - name: Install dependencies
        run: |
          apt update
          apt install -y curl sqlite3 libsqlite3-dev libsdl2-dev libvulkan-dev libvulkan1

      - name: Build Release
        run: swift build -c release

      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-artifacts-${{ matrix.swift }}-${{ github.run_id }}
          path: |
            *.lcov
            .build/*.yaml
            .build/**/*.a
            .build/**/*.so
            .build/**/*.dylib
            .build/**/*.dSYM
            .build/**/*.json
