name: Linux

on: workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  linux-test-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup private access
        run: |
          git config --global credential.helper ""
          git config --global --add credential.helper store
          echo "https://x-access-token:${{ secrets.GH_FIREBLADE_ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
          git config --global url."https://github.com/".insteadof git@github.com:
      - name: "Update APT"
        shell: bash
        run: "apt update"
      - name: "Install curl"
        shell: bash
        run: "apt-get install -y curl"
      - name: "Install system dependencies"
        shell: bash
        run: "apt-get -y install libvulkan-dev libsdl2-dev"
      - name: Swift version
        run: swift --version
      - name: Test
        run: swift test -v --skip-update --parallel --enable-test-discovery --enable-code-coverage
      - name: Build Release
        run: swift build -c release
